### ISSUE TITLE
Package sb-introspect doesn't exist

### ISSUE THREAD

**Issue by JulienVincenot** [tanders/cluster-engine#2]
Hi Torsten, 

So we met today with Örjan, worked mostly on the new interface (conceptually), then tried compiling the master. We got this error systematically, located in _000.main-interface.

I even tried updating SBCL from 1.5.3 to 2.0.4 but it didn't help.
For some reason, even after doing (require :sb-introspect), SBCL would always call an error.

In my local version I removed that line and then managed to compile a new .core file. Didn't try to evaluate anything yet.

If you have a cleaner workaround I'm interested. Thanks !

Julien

**Comment by tanders** [comment]
> We got this error systematically, located in _000.main-interface

Sorry, but how are you trying to compile or load the system and what error are you getting? Any more details ;-) 

I just tried the following on the master branch of cluster engine, and it loaded the system without problems (only remaining 68 style warnings and 15 notes, but nothing serious).

`(asdf:load-system :cluster-engine)`

I was using SBCL version 1.5.2 on a Mac.

**Comment by tanders** [comment]
... in case you are getting any type errors: I just noticed that in my current master branch there are still two un-pushed commits. One of that comments out some further unsuitable type declarations.

**Comment by tanders** [comment]
We discussed this matter by email, it was caused by the local setup.
